### ISSUE TITLE
Catch when key is missing on input CSV file

### ISSUE THREAD

**Issue by pabloab** [jkeenan/text-csv-hashify#4]
As said on [this StackOverflow answer](https://stackoverflow.com/a/49471620/4970442), [Text::CSV::Hashify](https://metacpan.org/pod/Text::CSV::Hashify) (v0.08) doesn't take care of uninitialized variables, in particular when user give a key not present on first row of CSV:

```
Use of uninitialized value $kk in hash element at /usr/local/share/perl/5.22.1/Text/CSV/Hashify.pm line 303, <$IN> line 2.
Use of uninitialized value $kk in hash element at /usr/local/share/perl/5.22.1/Text/CSV/Hashify.pm line 307, <$IN> line 2.
Use of uninitialized value $kk in hash element at /usr/local/share/perl/5.22.1/Text/CSV/Hashify.pm line 309, <$IN> line 2.
Use of uninitialized value $kk in hash element at /usr/local/share/perl/5.22.1/Text/CSV/Hashify.pm line 303, <$IN> line 3.
Use of uninitialized value $kk in concatenation (.) or string at /usr/local/share/perl/5.22.1/Text/CSV/Hashify.pm line 304, <$IN> line 3.
```

Would be nice to catch the situation and die with a helpful message.

**Comment by jkeenan** [comment]
Thanks for this report.  rt.cpan.org is the preferred issue tracker for my CPAN distributions, so I'm transferring discussion there and closing this github issue.

By my analysis there are **two** problems: one of code, the other of documentation.  They are respectively discussed in:
code: https://rt.cpan.org/Ticket/Display.html?id=125384
and
docs: https://rt.cpan.org/Ticket/Display.html?id=125385

Thank you very much.
Jim Keenan
